# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Platforms Subscription (549ce703-6bbc-47cc-ab10-41721551e2db)'
    subscriptionId: '549ce703-6bbc-47cc-ab10-41721551e2db'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'SAWYERR'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'